using HTTP 
using JSON
using Graphs
using URIParser
using URIs
import JLD2

const MATHEMATICS_CATEGORY = "Category:Mathematics"

function pull_wikipedia(output::String)
    category_pages = Dict{String, Vector{String}}()
    category_ids = Dict{String, Int64}()
    category_graph = DiGraph()

    # dict for categories to ignore
    non_math_categories = Set{String}([
        "Category:Population decline",
        "Category:Hindu astrology",
        "Category:Societal collapse",
        "Category:Four Yugas",
        "Category:Eastern Hemisphere",
        "Category:Hemispheres of Earth",
        "Category:Geopositioning markers",
        "Category:Geodynamics",
        "Category:Presidents of the International Union of Geodesy and Geophysics",
        "Category:Subduction",
        "Category:Television in China",
        "Category:Wikipedia categories named after British mathematicians",
        "Category:Ball games",
        "Category:Bermuda Triangle",
        "Category:Pyramids by continent",
        "Category:Navigation",
        "Category:Flying saucers",
        "Category:Southern celestial hemisphere",
        "Category:Ball (association football)",
        "Category:Pyramids by country",
        "Category:Orienteers",
        "Category:Orienteering",
        "Category:Thin films",
        "Category:Metal plating",
        "Category:Illuminated manuscripts",
        "Category:Flat Earth",
        "Category:Global Positioning System",
        "Category:Surveying",
        "Category:Topography",
        "Category:Mesoamerican pyramids",
        "Category:Surveying and geodesy markers",
        "Category:Hollow Earth",
        "Category:Geodesy organizations",
        "Category:Radio geopositioning",
        "Category:Geopositioning",
        "Category:Animals that use echolocation",
        "Category:Building automation",
        "Category:Elevators",
        "Category:Sonar",
        "Category:Positioning",
        "Category:Geographic position",
        "Category:Mechanisms (engineering)",
        "Category:Robot kinematics",
        "Category:Tetragonal crystals",
        "Category:Ceramic materials",
        "Category:Terracotta",
        "Category:Kepler space telescope",
        "Category:Cubic crystals",
        "Category:Crystals",
        "Category:Crystallography", # maybe sus?
        "Category:Fiction about black holes",
        "Category:Fiction about white holes",
        "Category:Fictional characters with density control abilities",
        "Category:Fictional characters who can turn intangible",
        "Category:Largest things by volume",
        "Category:Constellations listed by Ptolemy",
        "Category:Nucleons",
        "Category:Fermions",
        "Category:Potash",
        "Category:Copying",
        "Category:Wikidata",
        "Category:Wikipedia",
        "Category:Rankings",
        "Category:Height",
        "Category:Lists by length",
        "Category:Longest things",
        "Category:Tallest things",
        "Category:Dwarfism",
        "Category:Human height",
        "Category:Vertical extent",
        "Category:Skyscrapers",
        "Category:Lists of tallest buildings by continent",
        "Category:Highest things",
        "Category:Vertical position",
        "Category:Death deities",
        "Category:Religion and death",
        "Category:Destiny", # this is religious
        "Category:Interest rates",
        "Category:Friction musical instruments",
        "Category:Tribology",
        "Category:Bioelectricity",
        "Category:Dielectrics",
        "Category:Glass",
        "Category:Electric arcs",
        "Category:Electronic test equipment manufacturers",
        "Category:Geomagnetic storms",
        "Category:Lightning",
        "Category:Electricity",
        "Category:Electromagnetism",
        "Category:Power (physics)",
        "Category:Tools by power",
        "Category:Hand tools",
        "Category:Knives",
        "Category:Planes",
        "Category:Electric power",
        "Category:Electricity",
        "Category:Weight",
        "Category:Categories by frequency",
        "Category:Vehicles by speed",
        "Category:Fictional characters who can move at superhuman speeds",
        "Category:Road speed limit",
        "Category:Sex ratio",
        "Category:Matricides",
        "Category:Largest things by area",
        "Category:Aircraft weight measurements",
        "Category:Heaviest or most massive things",
        "Category:Mass spectrometry",
        "Category:Ion source",
        "Category:Thomson Medal recipients",
        "Category:Shrunken lakes",
        "Category:Hypertension",
        "Category:Blood pressure",
        "Category:Boilers",
        "Category:Pressure vessels",
        "Category:Boilers (cookware)",
        "Category:Boilermaking",
        "Category:Boilermakers",
        "Category:Vacuum",
        "Category:Vertical boilers",
        "Category:Pressure vessel components",
        "Category:Hyperloop",
        "Category:Temperature",
        "Category:Cold",
        "Category:Water",
        "Category:Havel",
        "Category:Hamburg",
        "Category:UBS",
        "Category:Asexual reproduction",
        "Category:First things",
        "Category:Individual physical objects",
        "Category:Monism",
        "Category:Monopoly (economics)",
        "Category:One-wheeled balancing robots",
        "Category:Sole survivors",
        "Category:Solo activities",
        "Category:Lists of things named after mathematicians",
        "Category:Pseudomathematics",
        "Category:Aerospace",
        "Category:Borders",
        "Category:Spatial cognition",
        "Category:Lists by distance",
        "Category:Places",
        "Category:Stereochemistry",
        "Category:Astronomical coordinate systems",
        "Category:Gyroscopes",
        "Category:Real object ordering",
        "Category:Vestibular system",
        "Category:Geodetic datums",
        "Category:Motion (physics)",
        "Category:Animal locomotion",
        "Category:Bats",
        "Category:Time",
        "Category:Paper",
        "Category:Paper art",
        "Category:Playing field surfaces",
        "Category:Decision theory",
        "Category:Mathematics fiction books",
        "Category:Paper folding",
        "Category:Magic figures",
        "Category:Mechanical puzzles",
        "Category:Evidence",
        "Category:Indicators",
        "Category:Legal reasoning",
        "Category:Moral psychology",
        "Category:Dice games",
        "Category:Games of chance",
        "Category:Fictional characters who can manipulate probability",
        "Category:Lists of things considered unusual",
        "Category:Luck",
        "Category:Targeting (warfare)",
        "Category:Targets and targeting",
        "Category:Risk",
        "Category:Probabilistic software",
        "Category:Rotating machines",
        "Category:Engines",
        "Category:Rotation-powered pulsars",
        "Category:Revolving restaurants",
        "Category:Rotating and whirling aerophones",
        "Category:Rotating disc computer storage media",
        "Category:Rotating ellipsoidal variables",
        "Category:Vortices",
        "Category:Satellites by orbit",
        "Category:Earth orbits",
        "Category:Orbits",
        "Category:Demographics",
        "Category:Demography",
        "Category:Insurance underwriters",
        "Category:Utility",
        "Category:Geographic information systems",
        "Category:Computer-aided design",
        "Category:Applications of distributed computing",
        "Category:Compression algorithms",
        "Category:Lossy compression algorithms",
        "Category:Audio codecs",
        "Category:Distributed computing",
        "Category:Fault tolerance",
        "Category:Biological invasions",
        "Category:Population ecology",
        "Category:Population genetics",
        "Category:Musical tuning",
        "Category:Psychometrics journals",
        "Category:Ecological metrics",
        "Category:Engineering ratios",
        "Category:Software metrics",
        "Category:Books about philosophy of mathematics",
        "Category:Philosophy of mathematics journals",
        "Category:Social statistics",
        "Category:Psychological methodology",
        "Category:Psychometrics",
        "Category:Quantitative psychologists",
        "Category:Computational astronomy",
        "Category:Computational fields of study",
        "Category:Computational chemists",
        "Category:Computational social scientists",
        "Category:GPGPU",
        "Category:Computational modeling journals",
        "Category:Fiction about artificial life",
        "Category:Artificial pets",
        "Category:Infographics",
        "Category:Self-replicating machines in fiction",
        "Category:Artificial Christmas trees",
        "Category:Science software",
        "Category:Scientific simulation software",
        "Category:Information visualization experts",
        "Category:Service-oriented (business computing)",
        "Category:Google services",
        "Category:Spreadsheet software",
        "Category:Human overpopulation",
        "Category:Industrial engineering",
        "Category:Management systems",
        "Category:Mathematical optimization in business",
        "Category:Combustion engineering",
        "Category:Broadcasting stations and networks",
        "Category:Internet culture",
        "Category:History of computer networks",
        "Category:Meteorological data and networks",
        "Category:Computer network technology",
        "Category:File sharing networks",
        "Category:Computer networks by scale",
        "Category:Cryptocurrencies",
        "Category:Streaming",
        "Category:Cloud storage",
        "Category:International road networks",
        "Category:Mobile telecommunications networks",
        "Category:Online video game networks",
        "Category:Social networks",
        "Category:Supply networks",
        "Category:Statistics profession and organizations",
        "Category:Statistical organizations",
        "Category:National statistical services",
        "Category:Official statistics",
        "Category:Censuses by country",
        "Category:Statistical data sets",
        "Category:Demographics indicators",
        "Category:Statistics of the COVID-19 pandemic",
        "Category:Vital statistics (government records)",
        "Category:Ecological connectivity",
        "Category:Electrical grid",
        "Category:Statistical data coding",
        "Category:Financial data analysis",
        "Category:Forecasting",
        "Category:Data journalism",
        "Category:Data journalists",
        "Category:Data brokers",
        "Category:Statistical regions",
        "Category:Economic indicators",
        "Category:Meteorological indices",
        "Category:Environmental indices",
        "Category:Rankings",
        "Category:Top lists",
        "Category:Lists of UN numbers",
        "Category:Lists of retired numbers",
        "Category:Lists of musical instruments by Hornbostel–Sachs number",
        "Category:Numbering in sports",
        "Category:Ship identification numbers",
        "Category:Telephone numbers",
        "Category:Chemical numbering schemes",
        "Category:Numerology",
        "Category:Superstitions about numbers",
        "Category:Bilingualism",
        "Category:Binary systems",
        "Category:Dimers (chemistry)",
        "Category:Duets",
        "Category:Duos",
        "Category:Flat horse races for two-year-old fillies",
        "Category:Flat horse races for two-year-olds",
        "Category:Second Triumvirate",
        "Category:Second-level domains",
        "Category:Double stars",
        "Category:Two-wheeled robots",
        "Category:3 (number)", # there are only like 2 relevant subcategories here and I am done
        "Category:First seven ecumenical councils",
        "Category:7 (number)",
        "Category:11 (number)",
        "Category:Binary compounds",
        "Category:Color",
        "Category:4 (number)",
        "Category:5 (number)",
        "Category:6 (number)",
        "Category:8 (number)",
        "Category:9 (number)",
        "Category:10 (number)",
        "Category:12 (number)",
        "Category:13 (number)",
        "Category:20 (number)",
        "Category:Centennial anniversaries",
        "Category:10,000 metres",
        "Category:Cyrillic script",
        "Category:Alphabets",
        "Category:Chinese character collation",
        "Category:Alphabetic lists",
        "Category:Character sets",
        "Category:Cyrillic alphabet representations",
        "Category:Latin-script representations",
        "Category:ASCII",
        "Category:Video games with textual graphics",
        "Category:Unicode",
        "Category:Unicode Transformation Formats",
        "Category:Whitespace",
        "Category:Braille",
        "Category:Character encoding",
        "Category:Units of measurement",
        "Category:Acoustic measurement",
        "Category:Aerosol measurement",
        "Category:Anthropometry",
        "Category:Astrometry",
        "Category:Audience measurement",
        "Category:Bibliometrics",
        "Category:Dating methods",
        "Category:Electrical measurement technology",
        "Category:Energy measurement",
        "Category:Flow meters",
        "Category:Geomatics",
        "Category:History of measurement",
        "Category:Indicators",
        "Category:Measuring instruments",
        "Category:Measurements and definitions of poverty",
        "Category:Photogrammetry",
        "Category:Surveys (human research)",
        "Category:Polling",
        "Category:Air intelligence",
        "Category:Earth observation",
        "Category:Intelligence assessment",
        "Category:Military intelligence collection",
        "Category:Latin squares",
        "Category:Citizen science",
        "Category:Observatories",
        "Category:Observational astronomy",
        "Category:Data collection satellites",
        "Category:Chemical tests",
        "Category:Citizenship tests",
        "Category:Electrical tests",
        "Category:Environmental testing",
        "Category:Test equipment",
        "Category:Examinations",
        "Category:Experiments",
        "Category:Examinations and testing in fiction",
        "Category:Fitness tests",
        "Category:Medical tests",
        "Category:Nondestructive testing",
        "Category:Product testing",
        "Category:Proving grounds",
        "Category:Psychological tests and scales",
        "Category:Readability tests",
        "Category:Soil tests",
        "Category:Test spaceflights",
        "Category:Special test",
        "Category:Standardized tests",
        "Category:Technology demonstrations",
        "Category:Test tracks",
        "Category:Weapon testing",
        "Category:Interest rates",
        "Category:Color scales",
        "Category:Hazard scales",
        "Category:Medical scales",
        "Category:Scales in meteorology",
        "Category:Musical scales",
        "Category:Time zones",
        "Category:Seismology measurement",
        "Category:Spectroscopy",
        "Category:Standards organizations",
        "Category:Timekeeping",
        "Category:Australian Aboriginal trackers",
        "Category:Motion capture actors",
        "Category:Colossal statues",
        "Category:Fiction about size change",
        "Category:Aircraft weight measurements",
        "Category:Heaviest or most massive things",
        "Category:Mass spectrometry",
        "Category:Weighing instruments",
        "Category:Megasites",
        "Category:Organism size",
        "Category:Sizes in clothing",
        "Category:Smallest things",
        "Category:Fiction about faster-than-light travel",
        "Category:Fiction about teleportation",
        "Category:Fiction about wormholes",
        "Category:Fictional dimensions",
        "Category:Buildings and structures by shape",
        "Category:Cross symbols",
        "Category:Meridians (geography)",
        "Category:Effects of gravity",
        "Category:Lists by size",
        "Category:Largest things",
        "Category:Lists of largest buildings and structures",
        "Category:Symbols by topic",
        "Category:Symbols by color",
        "Category:Symbols by date of introduction",
        "Category:Symbols by location",
        "Category:Lists of symbols",
        "Category:Astronomical symbols",
        "Category:Badges",
        "Category:Cantabrian symbols",
        "Category:Certification marks",
        "Category:Cockades",
        "Category:Diacritics",
        "Category:Emoticons",
        "Category:Fictional symbols",
        "Category:Flags",
        "Category:Heart symbols",
        "Category:Images of symbols",
        "Category:Mascots",
        "Category:Megalithic symbols",
        "Category:Oneirology",
        "Category:Optotypes",
        "Category:Pictograms",
        "Category:Star symbols",
        "Category:Typographical symbols",
        "Category:Visual motifs",
        "Category:Geocodes",
        "Category:Signage",
        "Category:Writing systems",
        "Category:Barcodes",
        "Category:Call signs",
        "Category:Color codes",
        "Category:Language of flowers",
        "Category:Line codes",
        "Category:Morse code",
        "Category:Soil classification",
        "Category:Musical notation",
        "Category:Arrangement",
        "Category:Compositions by instrumentation",
        "Category:Hell",
        "Category:Internet",
        "Category:Computer companies by year of disestablishment",
        "Category:Service companies by year of disestablishment",
        "Category:Financial services companies by year of disestablishment",
        "Category:Financial services companies disestablished in the 20th century",
        "Category:Financial services companies disestablished in 1981",
        "Category:History of computer companies",
        "Category:History of Google",
        "Category:History of YouTube",
        "Category:YouTube by decade",
        "Category:YouTube events by decade",
        "Category:History of computer science",
        "Category:Self",
        "Category:Consciousness",
        "Category:Mind–body problem",
        "Category:Belief",
        "Category:Communication of falsehoods",
        "Category:Bias",
        "Category:Media bias",
        "Category:Concentration of media ownership",
        "Category:Mass media by owner",
        "Category:Mass media families",
        "Category:Mass media families by nationality",
        "Category:Dialectic",
        "Category:Dialectical materialism",
        "Category:Conflict theory",
        "Category:Social stratification",
        "Category:Inheritance",
        "Category:Caste",
        "Category:Caste system by country",
        "Category:Philosophical logic"
    ])

    add_vertex!(category_graph)
    category_ids[MATHEMATICS_CATEGORY] = 1
    
    pull_category!(category_pages, category_ids, category_graph, non_math_categories, MATHEMATICS_CATEGORY, [MATHEMATICS_CATEGORY])

    JLD2.save_object(output, (category_pages, category_ids, category_graph))
end # function pull_wikipedia

function pull_category!(
    category_pages::Dict{String, Vector{String}},
    category_ids::Dict{String, Int64},
    category_graph::DiGraph,
    non_math_categories::Set{String},
    category_name::String,
    hist::Vector{String}
)
    # category_request_name = replace(category_name, " " => "_")
    category_request_name = escapeuri(category_name)
    url = "https://en.wikipedia.org/w/api.php?action=query&list=categorymembers&cmtitle=$(category_request_name)&format=json&cmlimit=200"

    println()
    @info "Hist: $hist"
    @info "Pulling category $category_name"
    
    # get and parse request
    r = HTTP.request("GET", url)
    j = JSON.parse(String(r.body))

    if !isnothing(get(j["query"], "continue", nothing)) 
        @error "Category $category_name has more than 200 category members!!"
    end # if

    category_pages[category_name] = Vector{String}() # should already be set

    categorymembers = j["query"]["categorymembers"]
    for category in categorymembers
        category = category["title"]

        # remove some bad categories
        if category in non_math_categories
            @warn "Skipping $category"
            continue
        end # if
        
        # split into when we have a category, and when we have just a page in the category
        # println(category)
        if startswith(category, "Category:")
            # if it doesn't already exist, then continue 
            if isnothing(get(category_ids, category, nothing))
                add_vertex!(category_graph) # add a graph vertex
                category_ids[category] = nv(category_graph)
            
                pull_category!(
                    category_pages,
                    category_ids,
                    category_graph,
                    non_math_categories,
                    category,
                    [hist..., category_name]
                )
            end # if

            add_edge!(
                category_graph,
                category_ids[category_name],
                category_ids[category]
            )
        else 
            push!(category_pages[category_name], category)            
        end # if
    end # for category
end # function pull_category
