using HTTP 
using JSON
using Graphs
using URIParser
using URIs
import JLD2

const MATHEMATICS_CATEGORY = "Category:Mathematics"

function pull_wikipedia(output::String)
    category_pages = Dict{String, Vector{String}}()
    category_ids = Dict{String, Int64}()
    category_graph = DiGraph()

    # dict for categories to ignore
    non_math_categories = Set{String}([
        "Category:Population decline",
        "Category:Hindu astrology",
        "Category:Societal collapse",
        "Category:Four Yugas",
        "Category:Eastern Hemisphere",
        "Category:Hemispheres of Earth",
        "Category:Geopositioning markers",
        "Category:Geodynamics",
        "Category:Presidents of the International Union of Geodesy and Geophysics",
        "Category:Subduction",
        "Category:Television in China",
        "Category:Wikipedia categories named after British mathematicians",
        "Category:Ball games",
        "Category:Bermuda Triangle",
        "Category:Pyramids by continent",
        "Category:Navigation",
        "Category:Flying saucers",
        "Category:Southern celestial hemisphere",
        "Category:Ball (association football)",
        "Category:Pyramids by country",
        "Category:Orienteers",
        "Category:Orienteering",
        "Category:Thin films",
        "Category:Metal plating",
        "Category:Illuminated manuscripts",
        "Category:Flat Earth",
        "Category:Global Positioning System",
        "Category:Surveying",
        "Category:Topography",
        "Category:Mesoamerican pyramids",
        "Category:Surveying and geodesy markers",
        "Category:Hollow Earth",
        "Category:Geodesy organizations",
        "Category:Radio geopositioning",
        "Category:Geopositioning",
        "Category:Animals that use echolocation",
        "Category:Building automation",
        "Category:Elevators",
        "Category:Sonar",
        "Category:Positioning",
        "Category:Geographic position",
        "Category:Mechanisms (engineering)",
        "Category:Tetragonal crystals",
        "Category:Ceramic materials",
        "Category:Terracotta",
        "Category:Kepler space telescope",
        "Category:Cubic crystals",
        "Category:Crystals",
        "Category:Crystallography", # maybe sus?
        "Category:Fiction about black holes",
        "Category:Fiction about white holes",
        "Category:Fictional characters with density control abilities",
        "Category:Fictional characters who can turn intangible",
        "Category:Largest things by volume",
        "Category:Constellations listed by Ptolemy",
        "Category:Nucleons",
        "Category:Fermions",
        "Category:Potash",
        "Category:Copying",
        "Category:Wikidata",
        "Category:Wikipedia",
        "Category:Rankings",
        "Category:Height",
        "Category:Lists by length",
        "Category:Longest things",
        "Category:Tallest things",
        "Category:Dwarfism",
        "Category:Human height",
        "Category:Vertical extent",
        "Category:Skyscrapers",
        "Category:Lists of tallest buildings by continent",
        "Category:Highest things",
        "Category:Vertical position",
        "Category:Death deities",
        "Category:Religion and death",
        "Category:Destiny", # this is religious
        "Category:Interest rates",
        "Category:Friction musical instruments",
        "Category:Tribology",
        "Category:Bioelectricity",
        "Category:Dielectrics",
        "Category:Glass",
        "Category:Electric arcs",
        "Category:Electronic test equipment manufacturers",
        "Category:Geomagnetic storms",
        "Category:Lightning",
        "Category:Electricity",
        "Category:Electromagnetism",
        "Category:Power (physics)",
        "Category:Tools by power",
        "Category:Hand tools",
        "Category:Knives",
        "Category:Planes",
        "Category:Electric power",
        "Category:Electricity",
        "Category:Weight",
        "Category:Categories by frequency",
        "Category:Vehicles by speed",
        "Category:Fictional characters who can move at superhuman speeds",
        "Category:Road speed limit",
        "Category:Sex ratio",
        "Category:Matricides",
        "Category:Largest things by area",
        "Category:Aircraft weight measurements",
        "Category:Heaviest or most massive things",
        "Category:Mass spectrometry",
        "Category:Ion source",
        "Category:Thomson Medal recipients",
        "Category:Shrunken lakes",
        "Category:Hypertension",
        "Category:Blood pressure",
        "Category:Boilers",
        "Category:Pressure vessels",
        "Category:Boilers (cookware)",
        "Category:Boilermaking",
        "Category:Boilermakers",
        "Category:Vacuum",
        "Category:Vertical boilers",
        "Category:Pressure vessel components",
        "Category:Hyperloop",
        "Category:Temperature",
        "Category:Cold",
        "Category:Water",
        "Category:Havel",
        "Category:Hamburg",
        "Category:UBS",
        "Category:Asexual reproduction",
        "Category:First things",
        "Category:Individual physical objects",
        "Category:Monism",
        "Category:Monopoly (economics)",
        "Category:Sole survivors",
        "Category:Solo activities",
        "Category:Lists of things named after mathematicians",
        "Category:Pseudomathematics",
        "Category:Aerospace",
        "Category:Borders",
        "Category:Spatial cognition",
        "Category:Lists by distance",
        "Category:Places",
        "Category:Stereochemistry",
        "Category:Astronomical coordinate systems",
        "Category:Gyroscopes",
        "Category:Real object ordering",
        "Category:Vestibular system",
        "Category:Geodetic datums",
        "Category:Motion (physics)",
        "Category:Animal locomotion",
        "Category:Bats",
        "Category:Time",
        "Category:Paper",
        "Category:Paper art",
        "Category:Playing field surfaces",
        "Category:Decision theory",
        "Category:Mathematics fiction books",
        "Category:Paper folding",
        "Category:Magic figures",
        "Category:Mechanical puzzles",
        "Category:Evidence",
        "Category:Indicators",
        "Category:Legal reasoning",
        "Category:Moral psychology",
        "Category:Dice games",
        "Category:Games of chance",
        "Category:Fictional characters who can manipulate probability",
        "Category:Lists of things considered unusual",
        "Category:Luck",
        "Category:Targeting (warfare)",
        "Category:Targets and targeting",
        "Category:Risk",
        "Category:Rotating machines",
        "Category:Engines",
        "Category:Rotation-powered pulsars",
        "Category:Revolving restaurants",
        "Category:Rotating and whirling aerophones",
        "Category:Rotating disc computer storage media",
        "Category:Rotating ellipsoidal variables",
        "Category:Vortices",
        "Category:Satellites by orbit",
        "Category:Earth orbits",
        "Category:Hyperbolic asteroids",
        "Category:Hyperbolic comets",
        "Category:Mars orbits",
        "Category:Orbit of the Moon",
        "Category:Orbital maneuvers",
        "Category:Suborbital spaceflight",
        "Category:Demographics",
        "Category:Demography",
        "Category:Insurance underwriters",
        "Category:Utility",
        "Category:Geographic information systems",
        "Category:Computer-aided design",
        "Category:Applications of distributed computing",
        "Category:Compression algorithms",
        "Category:Lossy compression algorithms",
        "Category:Audio codecs",
        "Category:Distributed computing",
        "Category:Fault tolerance",
        "Category:Biological invasions",
        "Category:Population ecology",
        "Category:Population genetics",
        "Category:Musical tuning",
        "Category:Psychometrics journals",
        "Category:Ecological metrics",
        "Category:Engineering ratios",
        "Category:Software metrics",
        "Category:Books about philosophy of mathematics",
        "Category:Philosophy of mathematics journals",
        "Category:Social statistics",
        "Category:Psychological methodology",
        "Category:Psychometrics",
        "Category:Quantitative psychologists",
        "Category:Computational astronomy",
        "Category:Computational fields of study",
        "Category:Computational chemists",
        "Category:Computational social scientists",
        "Category:GPGPU",
        "Category:Computational modeling journals",
        "Category:Fiction about artificial life",
        "Category:Artificial pets",
        "Category:Infographics",
        "Category:Self-replicating machines in fiction",
        "Category:Artificial Christmas trees",
        "Category:Science software",
        "Category:Scientific simulation software",
        "Category:Information visualization experts",
        "Category:Service-oriented (business computing)",
        "Category:Google services",
        "Category:Spreadsheet software",
        "Category:Human overpopulation",
        "Category:Industrial engineering",
        "Category:Management systems",
        "Category:Mathematical optimization in business",
        "Category:Combustion engineering",
        "Category:Broadcasting stations and networks",
        "Category:Internet culture",
        "Category:History of computer networks",
        "Category:Meteorological data and networks",
        "Category:Computer network technology",
        "Category:File sharing networks",
        "Category:Computer networks by scale",
        "Category:Cryptocurrencies",
        "Category:Streaming",
        "Category:Cloud storage",
        "Category:International road networks",
        "Category:Mobile telecommunications networks",
        "Category:Online video game networks",
        "Category:Social networks",
        "Category:Supply networks",
        "Category:Statistics profession and organizations",
        "Category:Statistical organizations",
        "Category:National statistical services",
        "Category:Official statistics",
        "Category:Censuses by country",
        "Category:Statistical data sets",
        "Category:Demographics indicators",
        "Category:Statistics of the COVID-19 pandemic",
        "Category:Vital statistics (government records)",
        "Category:Ecological connectivity",
        "Category:Electrical grid",
        "Category:Statistical data coding",
        "Category:Financial data analysis",
        "Category:Forecasting",
        "Category:Data journalism",
        "Category:Data journalists",
        "Category:Data brokers",
        "Category:Statistical regions",
        "Category:Economic indicators",
        "Category:Meteorological indices",
        "Category:Environmental indices",
        "Category:Rankings",
        "Category:Top lists",
        "Category:Lists of UN numbers",
        "Category:Lists of retired numbers",
        "Category:Lists of musical instruments by Hornbostel–Sachs number",
        "Category:Numbering in sports",
        "Category:Ship identification numbers",
        "Category:Telephone numbers",
        "Category:Chemical numbering schemes",
        "Category:Numerology",
        "Category:Superstitions about numbers",
        "Category:Bilingualism",
        "Category:Binary systems",
        "Category:Dimers (chemistry)",
        "Category:Duets",
        "Category:Duos",
        "Category:Flat horse races for two-year-old fillies",
        "Category:Flat horse races for two-year-olds",
        "Category:Second Triumvirate",
        "Category:Second-level domains",
        "Category:Double stars",
        "Category:First seven ecumenical councils",
        "Category:Trilogies",
        "Category:Trios",
        "Category:Three-base-unit banknotes",
        "Category:Border tripoints",
        "Category:Ternary computers",
        "Category:Triple deities",
        "Category:Flat horse races for three-year-olds",
        "Category:Harness races for three-year-olds",
        "Category:Medical triads",
        "Category:Three-volume novels",
        "Category:Three Pilgrimage Festivals",
        "Category:Three Rebellions in Shouchun",
        "Category:Triple stars",
        "Category:Tridents",
        "Category:Trilateral relations",
        "Category:Trilingualism",
        "Category:Trimers (chemistry)",
        "Category:Trinitarianism",
        "Category:Tritonic musical scales",
        "Category:First seven ecumenical councils",
        "Category:Heptagonal buildings",
        "Category:Heptatonic scales",
        "Category:Septets",
        "Category:Seven deadly sins",
        "Category:Seven Dwarfs",
        "Category:Seven hills of Rome",
        "Category:Seven in the Book of Revelation",
        "Category:Seven Sorrows of Mary",
        "Category:Seven virtues",
        "Category:Seven Wonders of the Ancient World",
        "Category:Title 11 of the United States Code",
        "Category:Binary compounds",
        "Category:Color",
        "Category:Flat horse races for four-year-old fillies",
        "Category:Flat horse races for four-year-olds",
        "Category:Four Worlds",
        "Category:Quadripoints and higher",
        "Category:Quartets",
        "Category:Tetralogies",
        "Category:Tetramers (chemistry)",
        "Category:Tetrapods",
        "Category:Pentalogies",
        "Category:Pentatonic scales",
        "Category:Quintets",
        "Category:Hexaemeron",
        "Category:Hexagonal buildings",
        "Category:Hexatonic scales",
        "Category:Sextets",
        "Category:Six-day events",
        "Category:Octagonal buildings",
        "Category:Octatonic scales",
        "Category:Octets",
        "Category:Fourth Way enneagram",
        "Category:Nonets",
        "Category:Compositions for decet",
        "Category:Decapodiformes",
        "Category:Decapolis",
        "Category:Decatonic scales",
        "Category:Fictional dectets",
        "Category:Minyan",
        "Category:Ten Commandments",
        "Category:Ten-base-unit banknotes",
        "Category:Ten-base-unit coins",
        "Category:Dii Consentes",
        "Category:Labours of Hercules",
        "Category:Twelve Olympians",
        "Category:Twelve Tribes of Israel",
        "Category:Twelve-tone technique",
        "Category:13 Kohanic cities",
        "Category:Thirteen Colonies",
        "Category:Triskaidekaphobia",
        "Category:Twenty-base-unit banknotes",
        "Category:Twenty-base-unit coins",
        "Category:Centennial anniversaries",
        "Category:10,000 metres",
        "Category:Cyrillic script",
        "Category:Alphabets",
        "Category:Chinese character collation",
        "Category:Alphabetic lists",
        "Category:Character sets",
        "Category:Cyrillic alphabet representations",
        "Category:Latin-script representations",
        "Category:ASCII",
        "Category:Video games with textual graphics",
        "Category:Unicode",
        "Category:Unicode Transformation Formats",
        "Category:Whitespace",
        "Category:Braille",
        "Category:Character encoding",
        "Category:Units of measurement",
        "Category:Acoustic measurement",
        "Category:Aerosol measurement",
        "Category:Anthropometry",
        "Category:Astrometry",
        "Category:Audience measurement",
        "Category:Bibliometrics",
        "Category:Dating methods",
        "Category:Electrical measurement technology",
        "Category:Energy measurement",
        "Category:Flow meters",
        "Category:Geomatics",
        "Category:History of measurement",
        "Category:Indicators",
        "Category:Measuring instruments",
        "Category:Measurements and definitions of poverty",
        "Category:Photogrammetry",
        "Category:Surveys (human research)",
        "Category:Polling",
        "Category:Air intelligence",
        "Category:Earth observation",
        "Category:Intelligence assessment",
        "Category:Military intelligence collection",
        "Category:Latin squares",
        "Category:Citizen science",
        "Category:Observatories",
        "Category:Observational astronomy",
        "Category:Data collection satellites",
        "Category:Chemical tests",
        "Category:Citizenship tests",
        "Category:Electrical tests",
        "Category:Environmental testing",
        "Category:Test equipment",
        "Category:Examinations",
        "Category:Experiments",
        "Category:Examinations and testing in fiction",
        "Category:Fitness tests",
        "Category:Medical tests",
        "Category:Nondestructive testing",
        "Category:Product testing",
        "Category:Proving grounds",
        "Category:Psychological tests and scales",
        "Category:Readability tests",
        "Category:Soil tests",
        "Category:Test spaceflights",
        "Category:Special test",
        "Category:Standardized tests",
        "Category:Technology demonstrations",
        "Category:Test tracks",
        "Category:Weapon testing",
        "Category:Interest rates",
        "Category:Color scales",
        "Category:Hazard scales",
        "Category:Medical scales",
        "Category:Scales in meteorology",
        "Category:Musical scales",
        "Category:Time zones",
        "Category:Seismology measurement",
        "Category:Spectroscopy",
        "Category:Standards organizations",
        "Category:Timekeeping",
        "Category:Australian Aboriginal trackers",
        "Category:Motion capture actors",
        "Category:Colossal statues",
        "Category:Fiction about size change",
        "Category:Aircraft weight measurements",
        "Category:Heaviest or most massive things",
        "Category:Mass spectrometry",
        "Category:Weighing instruments",
        "Category:Megasites",
        "Category:Organism size",
        "Category:Sizes in clothing",
        "Category:Smallest things",
        "Category:Fiction about faster-than-light travel",
        "Category:Fiction about teleportation",
        "Category:Fiction about wormholes",
        "Category:Fictional dimensions",
        "Category:Buildings and structures by shape",
        "Category:Cross symbols",
        "Category:Meridians (geography)",
        "Category:Effects of gravity",
        "Category:Lists by size",
        "Category:Largest things",
        "Category:Lists of largest buildings and structures",
        "Category:Symbols by topic",
        "Category:Symbols by color",
        "Category:Symbols by date of introduction",
        "Category:Symbols by location",
        "Category:Lists of symbols",
        "Category:Astronomical symbols",
        "Category:Badges",
        "Category:Cantabrian symbols",
        "Category:Certification marks",
        "Category:Cockades",
        "Category:Diacritics",
        "Category:Emoticons",
        "Category:Fictional symbols",
        "Category:Flags",
        "Category:Heart symbols",
        "Category:Images of symbols",
        "Category:Mascots",
        "Category:Megalithic symbols",
        "Category:Oneirology",
        "Category:Optotypes",
        "Category:Pictograms",
        "Category:Star symbols",
        "Category:Typographical symbols",
        "Category:Visual motifs",
        "Category:Geocodes",
        "Category:Signage",
        "Category:Writing systems",
        "Category:Barcodes",
        "Category:Call signs",
        "Category:Color codes",
        "Category:Language of flowers",
        "Category:Line codes",
        "Category:Morse code",
        "Category:Soil classification",
        "Category:Musical notation",
        "Category:Arrangement",
        "Category:Compositions by instrumentation",
        "Category:Hell",
        "Category:Internet",
        "Category:Computer companies by year of disestablishment",
        "Category:Service companies by year of disestablishment",
        "Category:Financial services companies by year of disestablishment",
        "Category:Financial services companies disestablished in the 20th century",
        "Category:Financial services companies disestablished in 1981",
        "Category:History of computer companies",
        "Category:History of Google",
        "Category:History of YouTube",
        "Category:YouTube by decade",
        "Category:YouTube events by decade",
        "Category:History of computer science",
        "Category:Self",
        "Category:Consciousness",
        "Category:Mind–body problem",
        "Category:Belief",
        "Category:Communication of falsehoods",
        "Category:Bias",
        "Category:Media bias",
        "Category:Concentration of media ownership",
        "Category:Mass media by owner",
        "Category:Mass media families",
        "Category:Mass media families by nationality",
        "Category:Dialectic",
        "Category:Dialectical materialism",
        "Category:Conflict theory",
        "Category:Social stratification",
        "Category:Inheritance",
        "Category:Caste",
        "Category:Caste system by country",
        "Category:Philosophical logic",
        "Category:Fluid power",
        "Category:Hydraulics",
        "Category:Hydraulic engineering",
        "Category:Sewerage",
        "Category:Anaerobic digestion",
        "Category:Biodegradation",
        "Category:Biodegradable materials",
        "Category:Wood",
        "Category:Woodworking",
        "Category:Carpentry",
        "Category:Carpenters",
        "Category:Jesus",
        "Category:Climate",
        "Category:Climate by continent",
        "Category:Climate change by continent",
        "Category:Gases",
        "Category:Atmosphere",
        "Category:Atmosphere of Earth",
        "Category:Air pollution",
        "Category:Air pollution emissions",
        "Category:Bioinformatics",
        "Category:Phylogenetics",
        "Category:Evolution of tetrapods",
        "Category:Evolution of mammals",
        "Category:Evolution of primates",
        "Category:Human evolution",
        "Category:Conceptual models",
        "Category:Economics models",
        "Category:Business models",
        "Category:Enterprise modelling",
        "Category:Organization design",
        "Category:Organizational structure",
        "Category:Organizational structure of political parties",
        "Category:Political party assemblies",
        "Category:Congresses of communist parties",
        "Category:Congress of the Communist Party of the Soviet Union",
        "Category:Central Committee of the Communist Party of the Soviet Union",
        "Category:Heads of the Communist Party of the Soviet Union",
        "Category:Biostatistics",
        "Category:Medical statistics",
        "Category:Epidemiology",
        "Category:Disease transmission",
        "Category:Infectious diseases by mode of transmission",
        "Category:Airborne diseases",
        "Category:COVID-19",
        "Category:COVID-19 pandemic",
        "Category:Wireless tuning and filtering",
        "Category:Radio spectrum",
        "Category:Digital broadcasting",
        "Category:Digital television",
        "Category:Streaming television",
        "Category:Original programming by streaming service",
        "Category:Control engineering",
        "Category:Applications of control engineering",
        "Category:Power control",
        "Category:Energy policy",
        "Category:Energy conservation",
        "Category:Sustainable transport",
        "Category:Rail transport", 
        "Category:Water waves",
        "Category:Tsunami",
        "Category:Tsunamis",
        "Category:Entertainment robots",
        "Category:Toy robots",
        "Category:Unmanned military aircraft",
        "Category:Cruise missiles",
        "Category:Adobe Flash",
        "Category:Flash cartoons",
        "Category:Flash television shows",
        "Category:British flash animated television series",
        "Category:Peppa Pig",
        "Category:Synchronized swimming",
        "Category:Synchronized swimming by continent",
        "Category:Synchronized swimming in Asia",
        "Category:Synchronized swimming in Asia by country",
        "Category:Simulation video games",
        "Category:Simulation video games by series",
        "Category:Strategic management",
        "Category:Communications management",
        "Category:Promotion and marketing communications",
        "Category:Advertising",
        "Category:Advertising characters",
        "Category:Corporate mascots",
        "Category:Magazine mascots",
        "Category:Climate change feedbacks",
        "Category:Land surface effects on climate",
        "Category:Mountain meteorology",
        "Category:Automated track-bound traffic",
        "Category:Automated guideway transit",
        "Category:People movers",
        "Category:People mover systems by country",
        "Category:People mover systems in the United States",
        "Category:Fictional robots",
        "Category:Fictional robots by franchise",
        "Category:Marvel Comics robots",
        "Category:Marvel Comics cyborgs",
        "Category:Iron Man",
        "Category:Works about robots",
        "Category:Fiction about robots",
        "Category:Fiction about artificial intelligence",
        "Category:Comics about artificial intelligence",
        "Category:Robot comics",
        "Category:Cyborg comics",
        "Category:Transhumanism in comics",
        "Category:Video games about artificial intelligence",
        "Category:Video games about robots",
        "Category:Overwatch",
        "Category:Fiction about drones",
        "Category:The Matrix (franchise)",
        "Category:Biorobotics in fiction",
        "Category:Biological models",
        "Category:Model organisms",
        "Category:Cell culture",
        "Category:Cell lines",
        "Category:Functional groups",
        "Category:Amines",
        "Category:Amino acids",
        "Category:3D films",
        "Category:3D films by decade",
        "Category:Corporate conduct",
        "Category:Corporate social responsibility",
        "Category:Sustainable business",
        "Category:Sustainable agriculture",
        "Category:Agroecology",
        "Category:Organic farming",
        "Category:Organic gardening",
        "Category:Nutrient pollution",
        "Category:Eutrophication",
        "Category:Intensive farming",
        "Category:Construction and management simulation games",
        "Category:Government simulation video games",
        "Category:Androids in fiction",
        "Category:Android (robot) video games",
        "Category:Terminator (franchise) video games",
        "Category:Fiction about cyborgs",
        "Category:Fictional cyborgs",
        "Category:Fictional extraterrestrial cyborgs",
        "Category:Fiction about augmented reality",
        "Category:Fiction about X-ray vision",
        "Category:Fictional characters with X-ray vision",
        "Category:Kryptonians",
        "Category:Superman",
        "Category:Capital management",
        "Category:Capital management firms",
        "Category:Hedge funds",
        "Category:Hedge fund firms of the United States",
        "Category:Hedge fund firms in New York City",
        "Category:Blackstone Inc.",
        "Category:Blackstone Inc. people",
        "Category:David Blitzer",
        "Category:Harris Blitzer Sports & Entertainment",
        "Category:Philadelphia 76ers",
        "Category:Fictional humanoid robots",
        "Category:Fictional gynoids",
        "Category:Home automation",
        "Category:Smart devices",
        "Category:Smartphones",
        "Category:Line of flagship smartphones",
        "Category:Video games with stereoscopic 3D graphics",
        "Category:Virtual Boy games",
        "Category:Financial capital",
        "Category:Initial public offering",
        "Category:Initial public offerings by century",
        "Category:20th-century initial public offerings",
        "Category:1990s initial public offerings",
        "Category:Factors of production",
        "Category:International factor movements",
        "Category:Foreign direct investment",
        "Category:Special economic zones",
        "Category:Special Economic Zones of China",
        "Category:Shenzhen", 
        "Category:Resources",
        "Category:Workforce",
        "Category:Fiction about holography",
        "Category:Holography in television",
        "Category:Steven Universe", 
        "Category:Digital cameras by brand", 
        "Category:Cameras by type",
        "Category:Cameras by format",
        "Category:Franchises",
        "Category:Hotel chains",
        "Category:Hotel chains by country",
        "Category:Holding companies",
        "Category:Holding companies by country",
        "Category:Holding companies of Canada",
        "Category:Corporate conduct",
        "Category:Exchange-traded products",
        "Category:Licensing",
        "Category:Trademarks",
        "Category:Virtual economy",
        "Category:Whistleblowing",
        "Category:Franchises",
        "Category:Management cybernetics",
        "Category:Instant messaging",
        "Category:Driving simulators",
        "Category:Aircraft simulators",
        "Category:Authentication",
        "Category:Identification",
        "Category:Identifiers",
        "Category:Names",
        "Category:Eponyms",
        "Category:Eponymous political ideologies",
        "Category:Leninism",
        "Category:Leninists",
        "Category:Anti-revisionists",
        "Category:Joseph Stalin",
        "Category:Stalinism",
        "Category:Anti-Stalinist left",
        "Category:Libertarian socialism",
        "Category:Anarchism",
        "Category:Anarchism by continent",
        "Category:Anarchism in Asia",
        "Category:Anarchism in Russia",
        "Category:Russian Revolution",
        "Category:Post–Russian Empire states",
        "Category:Estonia",
        "Category:Personal identification",
        "Category:Heraldry",
        "Category:Heraldic elements",
        "Category:Heraldic charges",
        "Category:Heraldic beasts",
        "Category:Medusa",
        "Category:Pegasus",
        "Category:Pegasoferae",
        "Category:Zooamata",
        "Category:Perissodactyla",
        "Category:Prehistoric Perissodactyla",
        "Category:Prehistoric horses",
        "Category:Miocene horses",
        "Category:Equini",
        "Category:Audio electronics",
        "Category:Digital audio",
        "Category:Voice over IP",
        "Category:VoIP companies",
        "Category:VoIP companies of the United States",
        "Category:Comcast",
        "Category:Comcast subsidiaries",
        "Category:NBCUniversal",
        "Category:E-commerce",
        "Category:Online companies",
        "Category:Online companies by country",
        "Category:Data security",
        "Category:Data protection",
        "Category:Data laws",
        "Category:Computer law",
        "Category:Internet governance",
        "Category:International Telecommunication Union",
        "Category:ITU-T recommendations",
        "Category:ITU-T Recommendations Series",
        "Category:ITU-T X Series Recommendations",
        "Category:OSI model",
        "Category:Galaxies",
        "Category:Fiction about galaxies",
        "Category:Milky Way in fiction",
        "Category:Fiction about the Solar System",
        "Category:Fiction about Earth",
        "Category:Europe in fiction",
        "Category:Fictional European people",
        "Category:Planetary systems",
        "Category:Star systems",
        "Category:Cryobiology",
        "Category:Electromagnetic components",
        "Category:Electromagnetic radiation",
        "Category:Light",
        "Category:Severe weather and convection",
        "Category:Coolants",
        "Category:Fictional characters with fire or heat abilities",
        "Category:Fire",
        "Category:Heating, ventilation, and air conditioning",
        "Category:Insulators",
        "Category:Refractory materials",
        "Category:Temperature",
        "Category:Thermal protection",
        "Category:Thermoregulation",
        "Category:Thermogenic plants",
        "Category:Torridness",
        "Category:Radiation",
        "Category:Fictional superorganisms",
        "Category:Acid–base chemistry",
        "Category:PH indicators",
        "Category:Psychrometrics",
        "Category:Atmospheric thermodynamics",
        "Category:Thermoelectricity",
        "Category:Calorimetry",
        "Category:Building thermal engineering",
        "Category:Engineering thermodynamics",
        "Category:Hot air engines",
        "Category:Fusion power",
        "Category:Fusion reactors",
        "Category:Security engineering",
        "Category:Prisons",
        "Category:Prison-related organizations",
        "Category:Prison and correctional agencies",
        "Category:Game theory game classes",
        "Category:Pursuit–evasion",
        "Category:Tag variants",
        "Category:Kabaddi",
        "Category:Word order",
        "Category:Languages by word order",
        "Category:Subject–verb–object languages",
        "Category:Chinese language",
        "Category:Chinese-language mass media",
        "Category:Transducers",
        "Category:Sensors",
        "Category:MOSFETs",
        "Category:Semiconductor device fabrication",
        "Category:Semiconductor companies",
        "Category:Semiconductor companies of Japan",
        "Category:Sony",
        "Category:Energy by continent",
        "Category:Electric power by continent",
        "Category:Electric power in Africa",
        "Category:Energy development",
        "Category:Alternative energy economics",
        "Category:Low-carbon economy",
        "Category:Electric vehicles",
        "Category:Electric public transport",
        "Category:Electric rail transport",
        "Category:Electric railways",
        "Category:Rapid transit",
        "Category:History of energy",
        "Category:Nuclear history",
        "Category:Nuclear warfare",
        "Category:Cold War",
        "Category:Aftermath of the Cold War",
        "Category:Post–Cold War era",
        "Category:1990s",
        "Category:1991",
        "Category:1991 by continent",
        "Category:1991 in Asia",
        "Category:Electrical resistance and conductance",
        "Category:Semiconductors",
        "Category:Semiconductor materials",
        "Category:Group IV semiconductors",
        "Category:Silicon",
        "Category:Silicon compounds",
        "Category:Silicates",
        "Category:Silicate minerals",
        "Category:Phyllosilicates",
        "Category:Clay",
        "Category:Heating",
        "Category:Residential heating",
        "Category:Fireplaces",
        "Category:Domestic and hearth deities",
        "Category:Household deities",
        "Category:Hera",
        "Category:Children of Hera",
        "Category:Ares",
        "Category:Women of Ares",
        "Category:Aphrodite",
        "Category:Consorts of Aphrodite",
        "Category:Dionysus",
        "Category:Companions of Dionysus",
        "Category:Satyrs",
        "Category:Energy by country",
        "Category:Electric power by country",
        "Category:Electric power infrastructure by country",
        "Category:Energy",
        "Category:Binding energy",
        "Category:Chemical energy",
        "Category:Nuclear energy",
        "Category:Radiation",
        "Category:Solar energy", 
        "Category:Blood pressure",
        "Category:Atmospheric pressure",
        "Category:Pressure gauges",
        "Category:Osmophiles",
        "Category:Piezophiles",
        "Category:Pressure vessels",
        "Category:Vacuum",
        "Category:Visibility",
        "Category:Wikipedia categories named after physical quantities",
        "Category:Seals (insignia)",
        "Category:Seals of cities and towns",
        "Category:Municipal heraldry of the United States",
        "Category:Seals of places in the United States", 
        "Category:Authentication methods in Iran",
        "Category:Age verification",
        "Category:Biometrics",
        "Category:Caller ID",
        "Category:Identification friend or foe",
        "Category:Identity documents",
        "Category:Message authentication codes",
        "Category:Password managers",
        "Category:Personal identification",
        "Category:Seals (insignia)",
        "Category:Shibboleths",
        "Category:Signature",
        "Category:Watermarking",
    ])

    add_vertex!(category_graph)
    category_ids[MATHEMATICS_CATEGORY] = 1
    
    pull_category!(category_pages, category_ids, category_graph, non_math_categories, MATHEMATICS_CATEGORY, [MATHEMATICS_CATEGORY])

    JLD2.save_object(output, (category_pages, category_ids, category_graph))
end # function pull_wikipedia

function pull_category!(
    category_pages::Dict{String, Vector{String}},
    category_ids::Dict{String, Int64},
    category_graph::DiGraph,
    non_math_categories::Set{String},
    category_name::String,
    hist::Vector{String}
)
    # category_request_name = replace(category_name, " " => "_")
    category_request_name = escapeuri(category_name)
    url = "https://en.wikipedia.org/w/api.php?action=query&list=categorymembers&cmtitle=$(category_request_name)&format=json&cmlimit=500"

    println()
    @info "Hist: $hist"
    @info "Pulling category $category_name"
    
    # get and parse request
    r = HTTP.request("GET", url)
    j = JSON.parse(String(r.body))

    if !isnothing(get(j["query"], "continue", nothing)) 
        @error "Category $category_name has more than 500 category members!!"
        throw(ErrorException("Category $category_name has more than 500 category members"))
    end # if

    category_pages[category_name] = Vector{String}() # should already be set

    categorymembers = j["query"]["categorymembers"]
    for category in categorymembers
        category = category["title"]

        # remove some bad categories
        if category in non_math_categories
            @warn "Skipping $category"
            continue
        end # if
        
        # split into when we have a category, and when we have just a page in the category
        # println(category)
        if startswith(category, "Category:")
            # if it doesn't already exist, then continue 
            if isnothing(get(category_ids, category, nothing))
                add_vertex!(category_graph) # add a graph vertex
                category_ids[category] = nv(category_graph)
            
                pull_category!(
                    category_pages,
                    category_ids,
                    category_graph,
                    non_math_categories,
                    category,
                    [hist..., category_name]
                )
            end # if

            add_edge!(
                category_graph,
                category_ids[category_name],
                category_ids[category]
            )
        else 
            push!(category_pages[category_name], category)            
        end # if
    end # for category
end # function pull_category
